# Generated by Django 4.1 on 2022-09-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('scheduledDateTime', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
