# Generated by Django 4.1 on 2022-09-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='description',
            new_name='title',
        ),
    ]
